openapi: 3.0.3
info:
  title: Pega
  description: O proxecto Pega ten o obxectivo de extraer e amosar datos electorais.
  version: 2.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /v1/comunidades-autonomas:
    get:
      summary: Lista de comunidades autónomas
      tags:
        - Divisions Administrativas
      responses:
        '200':
          $ref: '#/components/responses/DivisionsAdministrativas'
  /v1/comunidades-autonomas/{id}/provincias:
    get:
      summary: Lista de provincias dunha comunidade autónoma
      tags:
        - Divisions Administrativas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/DivisionsAdministrativas'
  /v1/provincias:
    get:
      summary: Lista de provincias
      tags:
        - Divisions Administrativas
      responses:
        '200':
          $ref: '#/components/responses/DivisionsAdministrativas'
  /v1/provincias/{id}/concellos:
    get:
      summary: Lista de concellos dunha provincia
      tags:
        - Divisions Administrativas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/DivisionsAdministrativas'
  /v1/concellos/import:
    post:
      summary: Importar concellos
      tags:
        - Divisions Administrativas
        - Administración
      requestBody:
        content:
          text/csv:
            schema:
              type: string
      responses:
        '200':
          description: OK
  /v1/procesos-electorais:
    get:
      summary: Listar procesos electorais
      tags:
        - Procesos Electorais
      parameters:
        - name: filter
          in: query
          schema:
            type: string
        - name: range
          in: query
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ProcesosElectorais'
    post:
      summary: Crear proceso electoral
      tags:
        - Procesos Electorais
        - Administración
      requestBody:
        $ref: '#/components/requestBodies/ProcesoElectoral'
      responses:
        '201':
          $ref: '#/components/responses/ProcesoElectoral'
  /v1/procesos-electorais/import:
    post:
      summary: Importar proceso electoral
      tags:
        - Procesos Electorais
        - Administración
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum:
              - infoelectoral
            default: infoelectoral
      requestBody:
        content:
          application/zip:
            schema:
              type: string
      responses:
        '200':
          description: OK
  /v1/procesos-electorais/tipos:
    get:
      summary: Lista de tipos de procesos electorais
      tags:
        - Procesos Electorais
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TipoProcesoElectoral'
  /v1/procesos-electorais/{id}:
    get:
      summary: Obter proceso electoral
      tags:
        - Procesos Electorais
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/ProcesoElectoral'
    put:
      summary: Modificar proceso electoral
      tags:
        - Procesos Electorais
        - Administración
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        $ref: '#/components/requestBodies/ProcesoElectoral'
      responses:
        '200':
          $ref: '#/components/responses/ProcesoElectoral'
    delete:
      summary: Eliminar proceso electoral
      tags:
        - Procesos Electorais
        - Administración
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted
  /v1/procesos-electorais/{id}/import:
    post:
      summary: Importar resultados dun proceso electoral
      tags:
        - Procesos Electorais
        - Administración
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum:
              - csv
            default: csv
      requestBody:
        content:
          application/binary:
            schema:
              type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    TipoProcesoElectoral:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
    DivisionAdministrativa:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
    ProcesoElectoral:
      type: object
      properties:
        id:
          type: integer
        typo:
          type: string
        data:
          type: string
          format: date
        ambito:
          type: string
        publicado:
          type: boolean
    ProcesosElectorais:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          typo:
            type: string
          data:
            type: string
            format: date
          ambito:
            type: string
          publicado:
            type: boolean
  responses:
    DivisionsAdministrativas:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/DivisionAdministrativa'
    ProcesoElectoral:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProcesoElectoral'
    ProcesosElectorais:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProcesosElectorais'
  requestBodies:
    ProcesoElectoral:
      content:
        application/json:
          schema:
            type: object
            properties:
              typo:
                type: integer
              data:
                type: string
                format: date
              ambito:
                type: integer
              publicado:
                type: boolean
  examples:
    ProcesosElectorais:
      value:
      - id: 1
        typo: 'Municipais'
        data: '2020-10-01'
        publicado: true
      - id: 2
        typo: 'Autonomicas'
        data: '2022-10-01'
        ambito: 'Galicia'
        publicado: false
